<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>dwrean.TV</AssemblyName>
    <RootNamespace>DwreanTv</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <ApplicationIcon>Assets\dwrean.ico</ApplicationIcon>
    <Version>0.3.1-test</Version>
    <Authors>Κυριάκος Οικονομίδης / dwrean.net</Authors>
    <Product>dwrean Ελληνική Τηλεόραση</Product>
    <Description>Portable εφαρμογή για δωρεάν ελληνικά τηλεοπτικά κανάλια.</Description>
  </PropertyGroup>

</Project>
