<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>dwrean.TV</AssemblyName>
    <RootNamespace>DwreanTv</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <ApplicationIcon>Assets\dwrean.ico</ApplicationIcon>
    <Version>0.2.1</Version>
    <Authors>Κυριάκος Οικονομίδης / dwrean.net</Authors>
    <Product>dwrean Ελληνική Τηλεόραση</Product>
    <Description>Portable IPTV player για δωρεάν ελληνικά τηλεοπτικά κανάλια.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>

</Project>
